### ISSUE TITLE
Incorrectly Identifies New 3ds color

### ISSUE THREAD

**Issue by ghagiel** [joel16/3DSident#21]
Reports my New 3DS XL black as red:

Do please let me know what info/logs/etc you need (not much familiar with 3ds stuff).

**Comment by joel16** [comment]
RED = New 3DS XL's code name (like how CTR is the code name for Old 3DS), it is not determining the colour. Considering this has been confusing a lot of users I may just decide to use the other code names instead. Also I notice your brightness says n3ds only, which is a bug and that will be fixed in the next release.

**Comment by ghagiel** [comment]
Understood, I'm a derp, and thx for the useful app!

**Comment by joel16** [comment]
No worries! BTW you may want to remove that first image since it displays a lot of your unique device info.

Also thanks for your donation, really appreciate it!

**Comment by ghagiel** [comment]
ofc!

**Comment by Goretantath** [comment]
Ah, glad i found this. Was going to make this exact post xd

**Comment by Masamune3210** [comment]
Believe me, I made this almost exact issue when I first got my N3DS XL :)
