### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by DarthVitrial** [joel16/3DSident#7]
While the program itself seems to work perfectly, when I try to exit back to the Homebrew Launcher (I'm using the 3dsx version of 3DSident) it crashes every time.
My reason for suspecting 3DSident instead of the homebrew channel as the culprit is that I have tested a number of other 3dsx apps (FBI, pksm, etc) with no crash. 

Entrypoint: HBlauncher_Loader 1.3
System: n3DS XL on 11.4 w/Luma 7.1 (B9S)
3DSident version 0.7.3 (GUI version)

Crash dump: 
https://mega.nz/#!Y4tHQCiC!LNe5PuzVXvnMLkpapbL4NC1pe1z1-l3eahHNaf198q8

**Comment by joel16** [comment]
This is probably because 3DSident uses a variety of services which can't be accessed by homebrew launcher. There's no way to fix this unless I scrap all the services which don't work in 3dsx format, sorry.

Also I did mention this in recent releases: " Also as always, 3DSX builds are no longer supported but they are here to assist in the downgrading process."

**Comment by DarthVitrial** [comment]
My apologies, I did not see that notice about them not being supported. Sorry to bother you.

**Comment by joel16** [comment]
No worries 👍
